title: 司法鉴定平台
subtitle: 基于大数据技术的快速分析系统
provider:
aversion: "0.0.1"

# 上传附件在服务器存储时的命名方式
upload_file_name: new # new=编码命名 / old=保留原文件名
forbid_shadow_login: true # 如果是TRUE，则同一个用户在同一时间只能有一个人在使用

# 是否使用CAS Server单点登录
use_cas_server: false

features:
  - [登录系统, session,"index,new,create,destroy", 'all']
  - [委托人注册, users,"new_consignor",'admin_user, client_entrust_user']
  - [编辑个人信息, users,"edit_self,update_edit_self", 'all']
  - [修改个人密码, users, "edit_password,update_password", 'all']
  - [用户浏览, users, "index,list", 'admin_user, center_admin_user, center_director_user']
  - [查看用户详细信息, users, "show", 'admin_user, center_admin_user, center_director_user']
  - [用户管理, users,"new,create,edit,update,destroy", 'admin_user, center_admin_user, center_director_user']
  - [注册审核管理, users,"confirm_users,confirm_user,edit_org", 'admin_user']
  - [重置用户密码, users,reset_password, 'admin_user, center_admin_user, center_director_user']
  - [科室管理, departments,"index,new,create,edit,update,destroy", 'center_admin_user, center_director_user']
  - [科室人员管理, departments,"add_users,add_users_submit,remove_user_from_department", 'center_admin_user, center_director_user']
  - [角色浏览, roles,index, 'admin_user, center_admin_user, center_director_user']
  - [角色管理, roles,"new,create,edit,update,destroy", 'admin_user']
  - [角色人员管理,roles,"add_users,add_users_submit,remove_user_from_role", 'admin_user, center_admin_user, center_director_user']
  - [权限浏览,features,"index,list", 'admin_user']
  - [权限角色授权,features,"add_features,add_features_submit,remove_feature_from_role", 'admin_user']
  - [日志管理,sys_logs,"index,show,search", 'admin_user']
  - [任务管理,delayed_jobs,"index", 'admin_user']
  - [参数配置,sys_configs,"index,show,new,create,edit,update,destroy", 'admin_user']
  - [个人事务提醒,notifications,"index,show,edit,all_readed,set_one_readed", 'all']
  - [机构管理, organizations,"index, new, edit, create, destroy, update", 'admin_user']
  - [编辑机构, organizations, 'edit, update', 'center_admin_user, center_director_user']
  - [科室模板管理, department_docs, "index, new, edit, create, destroy", 'center_admin_user, center_director_user']
  - [模板文档管理, doc_templates, "index, new, edit, create, destroy", 'admin_user']
  - [案件管理, main_cases, "index, new, edit, update, show, create, express_orders,
                           organization_and_user, matter_demands, generate_case_no,
                           matter_demands_and_case_types, filing_info, update_add_material,
                           update_filing, update_reject, open_barcode_image, create_case_doc,
                           payment_order_management, user_search, create_organization_and_user,
                           save_payment_order, request_bill, update_bill, update_case_stage,
                           case_executing, display_dynamic_file_modal, pending_cases, closing_case,
                           update_doc_is_passed, case_memos, create_case_memo, case_process_records,
                           update_financial_stage, personal_count, show_payment_order, print_transfer_doc_barcode, print_express_order_page",
                           'center_filing_user, center_department_director_user, center_ident_user, center_assistant_user, center_admin_user, center_director_user']
  - [我的案件, main_cases, "index, open_barcode_image, edit, filing_info, payment_order_management, print_transfer_doc_barcode,
                          case_executing, closing_case, case_memos, case_process_records", 'center_ident_user,
                                                                                            center_assistant_user,
                                                                                            center_department_director_user']
  - [本科室案件, main_cases, "department_cases, open_barcode_image, edit, update, filing_info, print_transfer_doc_barcode,
                            payment_order_management, case_executing, closing_case, case_memos, case_process_records", 'center_department_director_user, center_filing_user, center_ident_user, center_assistant_user']
  - [本机构的案件, main_cases, "center_cases, open_barcode_image, edit, filing_info, payment_order_management, print_transfer_doc_barcode,
                              case_executing, closing_case, case_memos, case_process_records", 'center_admin_user, center_director_user, center_director_user']
  - [财务人员案件查询, main_cases, "filed_unpaid_cases, open_barcode_image, edit, filing_info, print_transfer_doc_barcode,
                                 payment_order_management, case_executing, closing_case, case_memos, case_process_records, update_financial_stage", 'center_finance_user']
  - [财务统计, main_cases, "finance_check_cases, open_barcode_image, edit, filing_info, print_transfer_doc_barcode,
                                 payment_order_management, case_executing, closing_case, case_memos, case_process_records, update_financial_stage", 'center_finance_user']
  - [待归档的案件, main_cases, "apply_filing_cases, open_barcode_image, edit, filing_info, print_transfer_doc_barcode,
                              payment_order_management, case_executing, closing_case, case_memos, case_process_records", 'center_archivist_user']
  - [本科室已结案案件, main_cases, "department_closed_cases, open_barcode_image, edit, filing_info, payment_order_management, print_transfer_doc_barcode,
                                 case_executing, closing_case, case_memos, case_process_records", 'center_admin_user, center_director_user,
                                 center_director_user, center_filing_user, center_department_director_user, center_ident_user, center_assistant_user']
  - [已归档案件, main_cases, "my_closed_cases, open_barcode_image, edit, filing_info, payment_order_management, print_transfer_doc_barcode,
                               case_executing, closing_case, case_memos, case_process_records", 'center_admin_user, center_director_user,
                               center_director_user, center_filing_user, center_department_director_user, center_ident_user, center_assistant_user']
  - [鉴定周期管理, identification_cycles, 'index, new, edit, update, show, create, destroy', 'center_admin_user, center_director_user']
  - [补充材料周期管理, material_cycles, 'index, new, edit, update, show, create, destroy', 'center_admin_user, center_director_user']
  - [委托单管理, entrust_orders, 'index, new, edit, update, show, create, destroy', 'client_entrust_user']
  - [鉴定中心查看委托单, entrust_orders, 'org_orders, org_orders_unclaimed, show', 'center_director_user, center_filing_user, center_admin_user']
  - [到账记录管理, incoming_records, 'index, new, edit, update, show, create, destroy', 'center_finance_user, center_admin_user, center_director_user']
  - [到账记录认领, incoming_records, 'claim_record_list, claim_record_index, get_payment_order, claim_record', 'center_department_director_user, center_ident_user, center_assistant_user']
  - [案件缴费单管理, payment_orders, 'index, new, create, edit, destroy, update, submit_current_order, cancel_order', 'center_department_director_user, center_ident_user, center_assistant_user, center_admin_user, center_director_user']
  - [案件退费单管理, refund_orders, 'index, new, create, edit, destroy, update, submit_current_order, cancel_order', 'center_department_director_user,
                                                                                                                    center_ident_user,
                                                                                                                    center_assistant_user, center_admin_user, center_director_user']
  - [财务确认缴费单, payment_orders, 'finance_index, confirm_order, finance_show, print_page, finance_edit, finance_update, canceled_payment_orders', 'center_finance_user, center_admin_user, center_director_user']
  - [财务确认退费单, refund_orders, 'finance_index, confirm_order', 'center_finance_user, center_admin_user, center_director_user']
  - [申请开发票, bills, 'index, create, update, edit, new, destroy, dyn_form_modal, upload', 'center_department_director_user, center_ident_user, center_assistant_user']
  - [财务发票管理, bills, 'to_taked_away, to_billed, finance_index, dyn_form_modal, finance_create, finance_unBilled_index, upload', 'center_finance_user, center_admin_user, center_director_user']
  - [认领委托单, main_cases, 'new_with_entrust_order, update, matter_demands_and_case_types, create', 'center_filing_user, center_director_user, center_admin_user']
  - [发送快递, express_orders, 'index,create,edit,new,destroy,update', 'all']
  - [收到快递, recive_express_orders, 'index,create,edit,new,destroy,update', 'all']
  - [委托人查看案件, main_cases, 'wtr_cases, edit, case_memos, create_case_memo, case_process_records', 'client_entrust_user']
  - [统计, main_cases, 'personal_count', 'client_entrust_user,center_director_user,center_department_director_user']
  - [删除案件, main_cases, 'destroy', 'center_admin_user, center_director_user, center_department_director_user']

apps:
  - name: 系统管理
    module_chain:
#      - { controller: 'delayed_jobs', action: }
#      - { controller: 'sys_configs', action: }
      - { controller: 'users', action: }
      - { controller: 'departments', action: }
      - { controller: 'roles', action: }
      - { controller: 'features', action: }
#      - { controller: 'sys_logs', action: }
      - { controller: 'organizations', action: }
      - { controller: 'doc_templates', action: }
      - { controller: 'main_cases', action: }

#案由
anyou:
  - 医疗纠纷
  - 交通事故
  - 经济纠纷
  - 人身损害
  - 其它

# 案件性质
case_property:
  - 普通
  - 疑难
  - 复杂
  - 重大

#委托受理方式
accept_type:
  - 摇号
  - 送达
  - 自选

nationality:
  - 中国
  - 中国香港
  - 中国澳门
  - 中国台湾
  - 美国
  - 安道尔共和国
  - 阿拉伯联合酋长国
  - 阿富汗
  - 安提瓜岛及巴布达岛
  - 安圭拉岛
  - 阿尔巴尼亚
  - 亚美尼亚
  - 荷兰安的列斯群岛
  - 安哥拉
  - 南极洲
  - 阿根廷
  - 美国萨摩亚群岛
  - 奥地利
  - 澳大利亚
  - 阿鲁巴岛
  - 阿塞拜疆
  - 波斯尼亚
  - 巴巴多斯岛
  - 孟加拉国
  - 比利时
  - 布基纳法索
  - 保加利亚
  - 巴林岛
  - 布隆迪
  - 贝宁
  - 百慕大群岛
  - 玻利维亚
  - 巴西
  - 巴哈马
  - 不丹
  - 布维岛
  - 博茨瓦纳
  - 伯利兹城
  - 加拿大
  - 可可岛
  - 中非共和国
  - 刚果
  - 瑞士
  - 象牙海岸
  - 库克岛
  - 智利
  - 喀麦隆
  - 哥伦比亚
  - 哥斯达黎加
  - 前捷克斯洛伐克
  - 古巴
  - 佛得角
  - 圣诞节岛
  - 塞浦路斯
  - 捷克共和国
  - 德国
  - 丹麦
  - 多米尼加
  - 多米尼加共和国
  - 阿尔及利亚
  - 厄瓜多尔
  - 爱沙尼亚
  - 埃及
  - 西撒哈拉
  - 西班牙
  -  埃塞俄比亚
  - 芬兰
  - 斐济
  - 福克兰群岛
  - 密克罗西尼亚
  - 法罗群岛
  - 法国
  - 加蓬
  - 英国
  - 格林纳达
  - 乔治亚州
  - 法属圭亚那
  - 加纳
  - 直布罗陀
  - 格林兰
  - 冈比亚
  - 几内亚
  - 瓜德罗普岛
  - 赤道几内亚
  - 希腊
  - 危地马拉
  - 关岛
  - 几内亚比绍
  - 圭亚那
  - 洪都拉斯
  - 克罗地亚
  - 海地
  - 匈牙利
  - 印度尼西亚
  - 爱尔兰
  - 以色列
  - 印度
  - 伊拉克共和国
  - 伊朗
  - 冰岛
  - 意大利
  - 牙买加
  - 约旦
  - 日本
  - 肯尼亚
  - 吉尔吉斯坦
  - 柬埔寨
  - 基里巴斯
  - 克摩罗斯
  - 朝鲜
  - 韩国
  - 科威特
  - 科曼群岛
  - 哈撒克斯坦
  - 老挝
  - 黎巴嫩
  - 圣卢西亚岛
  - 列支敦士登
  - 斯里兰卡
  - 利比里亚
  - 莱索托
  - 立陶宛
  - 卢森堡公国
  - 拉脱维亚
  - 利比亚
  - 摩洛哥
  - 摩纳哥
  - 摩尔达维亚
  - 马达加斯加岛
  - 马绍尔群岛
  - 马其顿王国
  - 马里
  - 缅甸
  - 蒙古
  - 马提尼克岛
  - 毛利塔尼亚
  - 蒙特拉特岛
  - 马耳他
  - 毛里求斯
  - 马尔代夫群岛
  - 马拉维
  - 墨西哥
  - 马来西亚
  - 莫桑比克
  - 纳米比亚
  - 新苏格兰
  - 尼日尔
  - 诺福克岛
  - 尼日利亚
  - 尼加拉瓜
  - 荷兰
  - 挪威
  - 尼泊尔
  - 瑙鲁
  - 中立区
  - 纽埃岛
  - 新西兰
  - 阿曼
  - 巴拿马
  - 秘鲁
  - 玻利尼西亚
  - 巴布亚新几内亚
  - 菲律宾
  - 巴基斯坦
  - 波兰
  - 皮特克恩岛
  - 玻尔多尼加
  - 葡萄牙
  - 帕劳群岛
  - 巴拉圭
  - 卡塔尔
  - 罗马尼亚
  - 俄罗斯联邦
  - 卢旺达
  - 沙特阿拉伯
  - 所罗门群岛
  - 塞舌尔群岛
  - 苏丹
  - 瑞典
  - 新加坡
  - 圣特海伦拉
  - 斯洛文尼亚
  - 斯洛伐克共和国
  - 塞拉利昂
  - 圣马里诺
  - 塞内加尔
  - 索马里
  - 苏里拉马
  - 萨尔瓦多
  - 叙利亚共和国
  - 斯威士兰
  - 乍得
  - 多哥
  - 泰国
  - 塔吉克斯坦
  - 托克劳
  - 土库曼斯坦
  - 突尼斯
  - 东蒂汶
  - 土尔其
  - 特立尼达和多巴哥
  - 图瓦卢
  - 坦桑尼亚
