release_notes:
  - date: 2016-12-11
    note:
      - 优化数据分析模块性能，行业数据查询结果进行多维分析可以获得更快的性能
  - date: 2016-12-12
    note:
      - 升级数据分析搜索引擎，通过关键字搜索可以获得更加精确的搜索结果
      - BUG修复
  - date: 2017-01-05
    note: 
      - 优化行业查询，自动列出可查询关键字的字段
      - 修改系统日志列表布局
      - 更改登录页面样式
      - 工商行业数据查询使用新型的搜索引擎，提升性能和灵活度
  - date: 2017-01-10
    note:
      - 财政数据分析模块中增加财政支付数据流量分析功能
      - 行业数据搜索引擎现在可以支持多个关键字的检索（使用空格将多个关键字分开）
  - date: 2017-01-11
    note:
      - 更新工商数据分析算法，网络图中显示更多层次的关联关系节点
  - date: 2017-01-12
    note:
      - 整体更新系统外观风格
  - date: 2017-01-18
    note:
      - 增加政府采购数据查询功能
      - 增加政府采购数据分析功能，能够自动分析招投标信息中是否存在关联公司投标的情况
  - date: 2017-02-08
    note:
      - 全局数据查询功能，同时查询行业数据与系统中的文档内容
  - date: 2017-02-18
    note:
      - 增加政府采购供应商组合情况分析功能
  - date: 2017-02-28
    note:
      - 行业数据查询中，可以选择特定的数据表进行全文检索
  - date: 2017-03-28
    note:
      - 增加审计思路管理应用模块
      - 对行业数据检索的搜索引擎进行了全面优化，性能更快
      - 针对行业数据检索的关键字检索结果进行再次过滤时，可以更加精细的定制过滤条件，例如：可以指定多个关键字同时出现或者任意出现一个，可以指定某个关键字不能出现等
      - 针对行业数据检索结果，可以直接穿透到任意其他数据表进行查询
      - 优化了行业数据查询的结果多维分析功能，提升系统性能
      - 对系统应用模块进行重组，将高级数据分析功能重组为应用模块组
  - date: 2017-03-30
    note:
      - 升级多维分析组件，针对多维分析的结果，可以直接点击进行穿透查询
      - 升级多维分析组件，增加树状图显示
      - 升级多维分析组件，增加非重复计数、二项分布、两和之比、求和后取整等新的计算公式
  - date: 2017-05-02
    note:
      - 升级审计数据综合管理组件，在查看审计对象的财务数据中的凭证时，可以将当前凭证截图下载
      - 升级财务数据分析组件，跨年度科目余额分析以及财务数据多维分析的结果可以针对页面截图下载
      - 升级行业数据分析组件，多维分析结果可以截图下载
  - date: 2017-07-20
    note:
      - 全文检索结果增加排序功能
      - 优化系统首页面应用模块布局
  - date: 2017-09-28
    note: 
      - 增加数据索引管理功能模块
  - date: 2017-11-20
    note: 
      - 增加审计知识库功能模块
  - date: 2018-01-31
    note: 
      - 增加高级数据可视化功能模块
  - date: 2018-03-08
    note:
      - 增加审计疑点管理功能模块
  - date: 2018-05-02
    note: 
      - 被审计单位管理中，增加新建和编辑帐套的功能
  - date: 2018-06-30
    note:
      - 增加SQL查询功能模块
  - date: 2018-07-28
    note:
      - 增加外部数据源直接创建索引功能
  - date: 2018-08-10
    note: 
      - 系统根据授权可以分离成为“应用版”和“平台版”，分别具有不同级别的功能
  - date: 2018-09-10
    note: 
      - 系统数据索引管理模块可以正确识别Oracle的物化视图
  - date: 2018-09-27
    note:
      - 分析思路管理增加分析思路分类功能
      - 被审计单位管理功能进行优化，针对单位列表的搜索结果，用户可以选择同时显示上级（或者下级）单位
      - 数据索引管理模块中，可以设置某一数据表中的某一列是否显示
  - date: 2018-09-28
    note:
      - 导入财务数据包的时候，针对每一张表都填充所属核算级次，并创建/更新相应的索引
  - date: 2018-10-22
    note: 
      - 增加分析模型APP，在系统中可以创建分析模型并按权限进行浏览
  - date: 2018-10-23
    note:
      - SQL数据分析APP中，增加对字段的数值计算的支持
  - date: 2018-11-06
    note:
      - 增加智能关联规则挖掘APP 
  - date: 2018-11-12
    note:
      - 增加智能K邻近聚类分析APP 
  - date: 2018-11-24
    note:
      - 增加用户上传文件分析APP，可以对用户上传的Excel文件进行导入并分析
  - date: 2018-11-28
    note: 
      - 恢复公告管理APP
      - 恢复消息管理APP
      - 恢复平台个人事务提醒功能接口
  - date: 2018-12-11
    note:
      - 增加审计计划管理APP
  - date: 2018-12-16
    note: 
      - 增加被审计单位门户的支持
  - date: 2018-12-24
    note: 
      - 增加审计整改跟踪APP
      - 被审计单位可以在线完善自身信息
  - date: 2018-12-28
    note: 
      - 增加审计问题库管理功能
      - 增加审计事项库管理功能
      - 增加审计文档模板库管理功能
  - date: 2018-12-29
    note:
      - 被审计单位管理APP：可以批量导入部门结构信息对被审计单位信息进行初始化
  - date: 2019-01-08
    note:
      - 增加审计项目管理子系统
      - 石刻平台实现与审计项目管理子系统单点登录
  - date: 2019-01-10
    note:
      - 审计项目管理APP中增加审计问题管理功能
      - 审计项目计划与审计项目子系统进行关联
  - date: 2019-01-19
    note:
      - 分析疑点可以关联被审计单位和审计项目
  - date: 2019-02-14
    note: 
      - 审计项目管理子系统中，增加项目模板功能，用户可以根据项目模板创建项目
