# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# redis: &redis
#    redis_server: 'localhost'
#    redis_port: 6379
#    redis_db_num: 0
#    redis_namespace: 'highlander_sidekiq'

development:
  # <<: *redis
  secret_key_base: 282ff9699e394c0573f70a4ee3018c38e23e94aec0762267657affa050e32722e27ba41c1955ff3f7f4f73d3e8ef90a5c71d1ff6848341f74940f9618bc421c9

test:
  secret_key_base: c2263e9cf41a48635a6cc2a9c399b2ac157da50433f1f02965a9b742cf88b88f8998c94159d73ae8623d4d02d04f7d4f622e83b25d74f756d26ea10be54096d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 9ef3ffcdfb80c46444b88896b1e582da168263ff090d230dd76fab3076235d8299291339e80b796c6aeaeb7017b586278a86ae88263af82747ff0b28a910cf1e
  
